### ISSUE TITLE
Probable Bug with SDP building in RTCPeerConnection createAnswer()

### ISSUE THREAD

**Issue by benharp** [shinyoshiaki/rainy-webrtc#337]
Hello, and thank you for this great WebRTC implementation! It has been very useful, and great for learning.

I'm building a werift server that communicates media to and from a Chrome browser, and getting the following error in Chrome: 

> DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: A BUNDLE group in answer contains a MID='2av' that was not in the offered group.

This seems to only happen when werift has an "inactive" transceiver in its list and receives an offer from the Chrome side. (I have inactive transceivers after adding and later removing tracks on the werift side, and Chrome sends an offer when I add a track from the Chrome side.)

Looking closer at the offer and answer SDP provided, Chrome includes _only_ active transceivers in the bundle group for its offer, but werift's answer includes _all_ transceivers, active or inactive, and Chrome throws a fit.

Chrome's offer: `a=group:BUNDLE 0av 0`
werift's answer: `a=group:BUNDLE 0av 0 2av`

I'm assuming this is unintended, as looking at the code, `peerConnection's createOffer()` does correctly filter inactive transceivers out of the SDP offer, but `peerConnection's createAnswer()`  doesn't.

Working correctly:
https://github.com/shinyoshiaki/werift-webrtc/blob/3fed6d5fabb82f5220d84b3a1f1dbe2a10540ae6/packages/webrtc/src/peerConnection.ts#L363-L368
vs working incorrectly:
https://github.com/shinyoshiaki/werift-webrtc/blob/3fed6d5fabb82f5220d84b3a1f1dbe2a10540ae6/packages/webrtc/src/peerConnection.ts#L1370

If this should be fixed, I'm happy to try my hand at a pull request, but I figured I'd ask first as I'm still new to werift, WebRTC, and Open Source in general.
If this is intended, or shouldn't be happening in the first place, I'd be grateful for any other advice on why this might be happening. Thank you.

**Comment by shinyoshiaki** [comment]
I will investigate later.

> I'm happy to try my hand at a pull request, but I figured I'd ask first as I'm still new to werift, WebRTC, and Open Source in general.

If you have code that reproduces the problem and patches to fix it, you can send a PullRequest directly.
