### ISSUE TITLE
Compatibility Safari

### ISSUE THREAD

**Issue by temaivanoff** [shinyoshiaki/rainy-webrtc#346]

**Comment by shinyoshiaki** [comment]
?

**Comment by temaivanoff** [comment]
![image](https://github.com/shinyoshiaki/werift-webrtc/assets/11176223/3beff248-c416-42a6-ac15-6bb17d8a619f)

**Comment by diogeneshamilton** [comment]
Also curious about this, seen some odd behavior in Safari, where it crashes the server because of wrong nonce, never seems to happen on Chrome.

**Comment by koush** [comment]
It's compatible with safari. I use it extensively with Safari.
