### ISSUE TITLE
Security issue: outdated cryptography is used

### ISSUE THREAD

**Issue by paulmillr** [shinyoshiaki/rainy-webrtc#357]
You're using elliptic, which has long been unmaintained, and has a few cases where it produces invalid outputs, which means in blockchain context "users lose money".

It is advised to replace it with **audited** `@noble/curves`.

**Comment by shinyoshiaki** [comment]
Thanks for the advice. I'll try to migration.

**Comment by shinyoshiaki** [comment]
done it #358

**Comment by paulmillr** [comment]
not done. you didnt remove elliptic

**Comment by shinyoshiaki** [comment]
finally #359
