### ISSUE TITLE
Missing peerConnection.close() method

### ISSUE THREAD

**Issue by ibc** [shinyoshiaki/rainy-webrtc#4]
The [peerConnection.ts](https://github.com/shinyoshiaki/rainy-webrtc/blob/master/src/rtc/peerConnection.ts) file lacks `close()` method, which IMHO is a very basic method in `RTCPeerConnection`.

**Comment by shinyoshiaki** [comment]
That's for sure.
I will be implementing "close()" as a priority.

**Comment by shinyoshiaki** [comment]
I implemented peerconnection.close()  and datachannel.close() .
I tested them with chrome.

Please mention me if there seems to find some problem.
