### ISSUE TITLE
incorrect ordering of candidate pairs

### ISSUE THREAD

**Issue by geirbakke** [shinyoshiaki/rainy-webrtc#413]
**Describe the bug**
I think the ordering of candidate pairs is wrong and should be reversed. As it is now it will prioritise relay candidates.
in `sortCandidatePairs` in `ice.ts`

**Reproduction Code**
Log checkList after sortCandidatePairs.
Relay candidates tends to be nominated

**Comment by shinyoshiaki** [comment]
Thanks for the report.It is indeed reversed and will be corrected.

**Comment by shinyoshiaki** [comment]
fixed at #422

**Comment by geirbakke** [comment]
thx, impressive work this lib
